export {default as Home} from './Home'
export {default as About} from './About'
export {default as Mission} from './Mission'
export {default as Vision} from './Vision'
export {default as Teams} from './Teams'
export {default as Partners} from './Partners'
export {default as Services} from './Services'
