export {default as Header} from './Header'
export {default as NavBar} from './NavBar'
export {default as Section} from './Section'
export {default as Slider} from './Slider'
export {default as Footer} from './Footer'